export default [
    {
        name: 'OBJECTID',
        type: 'esriFieldTypeOID',
        alias: 'OBJECTID',
        sqlType: 'sqlTypeOther',
        nullable: false,
        editable: false,
        visible: true,
        domain: null,
        defaultValue: null
    },
    {
        name: 'GEOID20',
        type: 'esriFieldTypeString',
        alias: 'GEOID20',
        sqlType: 'sqlTypeOther',
        length: 15,
        nullable: true,
        editable: true,
        visible: true,
        domain: null,
        defaultValue: null
    },
    {
        name: 'P0010001',
        type: 'esriFieldTypeDouble',
        alias: 'Total Population',
        sqlType: 'sqlTypeOther',
        nullable: true,
        editable: true,
        visible: true,
        domain: null,
        defaultValue: null
    },
    {
        name: 'P0010003',
        type: 'esriFieldTypeDouble',
        alias: 'White alone',
        sqlType: 'sqlTypeOther',
        nullable: true,
        editable: true,
        visible: true,
        domain: null,
        defaultValue: null
    },
    {
        name: 'P0010004',
        type: 'esriFieldTypeDouble',
        alias: 'Black or African American alone',
        sqlType: 'sqlTypeOther',
        nullable: true,
        editable: true,
        visible: true,
        domain: null,
        defaultValue: null
    },
    {
        name: 'P0010005',
        type: 'esriFieldTypeDouble',
        alias: 'American Indian and Alaska Native alone',
        sqlType: 'sqlTypeOther',
        nullable: true,
        editable: true,
        visible: true,
        domain: null,
        defaultValue: null
    },
    {
        name: 'P0010006',
        type: 'esriFieldTypeDouble',
        alias: 'Asian alone',
        sqlType: 'sqlTypeOther',
        nullable: true,
        editable: true,
        visible: true,
        domain: null,
        defaultValue: null
    },
    {
        name: 'P0010007',
        type: 'esriFieldTypeDouble',
        alias: 'Native Hawaiian and Other Pacific Islander alone',
        sqlType: 'sqlTypeOther',
        nullable: true,
        editable: true,
        visible: true,
        domain: null,
        defaultValue: null
    },
    {
        name: 'P0010008',
        type: 'esriFieldTypeDouble',
        alias: 'Some Other Race alone',
        sqlType: 'sqlTypeOther',
        nullable: true,
        editable: true,
        visible: true,
        domain: null,
        defaultValue: null
    },
    {
        name: 'P0020002',
        type: 'esriFieldTypeDouble',
        alias: 'Hispanic or Latino',
        sqlType: 'sqlTypeOther',
        nullable: true,
        editable: true,
        visible: true,
        domain: null,
        defaultValue: null
    },
    {
        name: 'P0030001',
        type: 'esriFieldTypeDouble',
        alias: 'Voting Age 18+',
        sqlType: 'sqlTypeOther',
        nullable: true,
        editable: true,
        visible: true,
        domain: null,
        defaultValue: null
    },
    {
        name: 'P0050001',
        type: 'esriFieldTypeDouble',
        alias: 'Group Quarters',
        sqlType: 'sqlTypeOther',
        nullable: true,
        editable: true,
        visible: true,
        domain: null,
        defaultValue: null
    },
    {
        name: 'Shape__Area',
        type: 'esriFieldTypeDouble',
        alias: 'Shape__Area',
        sqlType: 'sqlTypeDouble',
        nullable: true,
        editable: false,
        visible: true,
        domain: null,
        defaultValue: null
    },
    {
        name: 'Shape__Length',
        type: 'esriFieldTypeDouble',
        alias: 'Shape__Length',
        sqlType: 'sqlTypeDouble',
        nullable: true,
        editable: false,
        visible: true,
        domain: null,
        defaultValue: null
    },
    {
        name: 'District',
        type: 'esriFieldTypeInteger',
        alias: 'Supervisor District',
        sqlType: 'sqlTypeOther',
        nullable: true,
        editable: true,
        visible: true,
        domain: null,
        defaultValue: null
    },
    {
        name: 'Incorporated',
        type: 'esriFieldTypeString',
        alias: 'Incorporated Block',
        sqlType: 'sqlTypeOther',
        nullable: true,
        editable: true,
        visible: true,
        domain: null,
        defaultValue: null
    },
]
